// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sovzhkfnhjnawqdegmty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdnpoa2ZuaGpuYXdxZGVnbXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTgwMTksImV4cCI6MjA1NzY3NDAxOX0.XChDB_bBff-mbSA_elGhMPZsD-wz0-blHfwKqn3ILW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);